### ISSUE TITLE
Listview holds position on page or forum change

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#285]
In the thread view, if you click the next page button while at the bottom of the page, it takes you to the bottom of the next page instead of the top. Is this a known bug? 

- Vykk.Draygo

**Comment by baka-kaba** [comment]
Took a look at this, it's just that the listview needed scrolling back to the top when its content is changed.

I made it so it jumps immediately, which is the most consistent experience - it's possible to set a smooth scroll animation to position 0, which feels a bit better to me (it makes it clear you're moving back to the top of the view) but it gets interrupted when you move to an uncached page.

I think the scrolling can be done, but since the load is async (and used for stuff that shouldn't reset the position, like refreshing or bookmarking) it'll need some extra handling when it's completed. I figured I'd just put this up and see what people think first. If you want to try the smooth scroll, change the code I added to `mListView.smoothScrollToPosition(0);` - it works on thread list pages you've already loaded before

**Comment by Sereri** [comment]
I did a similar change in syncForum() like a day before you did, I hope it doesn't lead to problems

**Comment by baka-kaba** [comment]
Yeah that looks like it's probably fine to me - my fix immediately resets the position, and yours changes it again not long after, so they shouldn't interfere. If there was smooth scrolling involved it would probably interrupt it, but right now it seems fine.

`syncForum()`would be a better place for it really, but when you switch pages in a forum it needs to call `refreshInfo()` first to make sure you get an immediate visual swap to a new page, so there definitely needs to be a position reset before that happens too, so the way things are right now I think you need both fixes!

I'll give it a test anyway
