### ISSUE TITLE
Replace Tree-view-list-android with ExpandableListView

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#329]
This means we can't display a third level anymore but I guess it's worth not dealing with its shit anymore

**Comment by Sereri** [comment]
Gave this a shot in 5ee7df1fe7a2e015582258f253528e448cd47601 ,maybe someone (@baka-kaba ?) can take a look? It's probably terrible and redundant in some places

**Comment by baka-kaba** [comment]
Yeah this seems to work great, and who cares if a forum is a subforum within a subforum? It already feels better with the autoscroll too

Hope you don't mind, I had a play around while I was meant to be doing something else - I squished a bunch of the adapter code together and made a separate layout and styles for the main/sub forums, and tried putting an accent colour on the dropdown too. It's mostly to make it easier to mess around with. 40b65eb1d4fcc64ecae49973d9d1802b844fc74f

I think the subforums definitely need *some* distinction though, they look a bit weird when they're fully left-aligned and the same font as the mains. They almost look more important because the tag isn't indenting them. I'll have a very quick go at crowbarring in the square forum tags too, if it's like the thread tags it should be doable, see how it looks
