### ISSUE TITLE
Parse and display Announcements

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#366]
Should appear with the rest of the threads, always on top, maybe marked somehow

**Comment by baka-kaba** [comment]
I did the announcements, but not in the thread list. I thought it needed doing quickly since nobody knows what's going on unless they look at the main site

6558fa8e

It works like the private message detector - whenever a thread list is parsed it looks for new announcements, and pops up a snackbar if it finds any. You can get to them from the nav drawer and there's an unread counter. The actual announcements are just an activity that pops up and uses a weird thread view - I didn't do anything special with it so it could be a dialog if you wanted

Anyhow give it a look if you like, I found out the forums' announcement timestamps bounce between timezones for... reasons so I had to keep lists of titles instead. I just finished that so I'm going to test it for a while (there's diagnostic stuff in there I want to keep an eye on) but I think it's working now

**Comment by Sereri** [comment]
I'll give it a try when I get home.

My thoughts at first glance:
I know you already built this AnnouncementActivity, but to be honest I'd rather go for an integration into the thread list. I don't know about displaying them as well, doing that in the DisplayThreadFragment could be a bad idea.
Maybe the Announcements could be, once detected, injected into the thread loading process. Like, ask the Annouchment Manager whether there are announcements, inject them into the List at the start if there are, do nothing if there are none. That way you can re-read an announcement.

**Comment by baka-kaba** [comment]
Yeah I agree, and that's what I was working towards at first - changing the thread list so it's more like the forum one, having a collapsible category at the top with announcements, and having them display in the thread view

Trouble is there's a lot of stuff in the way of that, things hardcoded a specific way so you have to do a lot of work to ram in the new functionality and make it handle extra cases (even more if you want to try and make it more generalised and flexible)

Honestly I just wanted to get something working and out there. There've been a bunch of important announcements lately - forums changing, warnings about security and public information - that people on the app are completely unaware of. So I feel like it's better to get something barebones but functional up and running, and work on making it nice and slick later

**Comment by baka-kaba** [comment]
But that said, after using this for a bit it's not a bad solution the way it is. You rarely need to read announcements, so there's a logic to making them accessible through the navigation drawer (with the other occasional stuff like PMs and Settings). Having them permanently take up space at the top of every thread list matches how the site does it, but now I'm not sure it's the best thing to do here

It might be worth doing what the PM manager does - as well as showing a snackbar when there's a new announcement, pop one up on app startup if there are announcements the user hasn't looked at yet. There's an unread counter in the nav drawer, but this would push it in your face. Might be a good compromise vs keeping them resident in the thread list

Announcements are sort of messed up - the links on the thread list have different titles, but they all link to the top of same page. That page looks kind of like a thread with posts in it, but the structure is different. The activity I made is super basic - it just displays that page using our formatting and handles the internal and external links properly. It can definitely be improved, but some of the nice changes would probably involve adding functionality that doesn't exist on the main site, like linking announcement titles to actual announcements. And that means dodging the Radium traps too

**Comment by Sereri** [comment]
After testing, this is working well, feel free to merge it in.
