### ISSUE TITLE
Attempting to scroll on a [code] block brings up the bookmark panel

### ISSUE THREAD

**Issue by natchapman** [Awful/Awful.apk#438]
When scrolling through a thread, if my finger is in a [code] block, the app acts as though I have swiped right and opens up the bookmark panel. I'm running Awful 3.2.3.2 on CM11, using an Amazon Fire Phone. Please let me know if I can provide any additional information.

**Comment by Sereri** [comment]
Could be "solved" by disabling the code-tag swipe-lock at the bottom of a page. But then you could not scroll those very well. vOv

**Comment by baka-kaba** [comment]
I think I have a better idea of what's going on now. The javascript is calling the ``enableSwipe`` method, so its ``touchEvent`` is ending even while your finger is on the element. I'm not sure, but I'm assuming something like this is happening:
- the ``SwipeRefreshLayout`` is allowing touch events to pass through to the webview, so long as it can still scroll
- this lets the webview consume touch events on things like code blocks, and it can block the view pager from consuming horizontal swipes
- but when the webview hits the top or bottom and you're still dragging, the ``SwipeRefreshLayout`` takes over the touch event and stops passing it through, so it can handle the pull-to-refresh gesture
- the webview stops receiving touch events, so the javascript fires its "touch event ended" callbacks and sets swiping enabled on the viewpager
- the viewpager, which has been ignoring motion events up until now, suddenly gets an ``ACTION_MOVE`` event with a horizontal offset (i.e. from where the touch event started)
- it reads this as a sudden horizontal swipe, and basically drags the pager across by that amount

you can see this kind of behaviour by swiping horizontally by different amounts before you swipe up - the pager pops out by about the same amount. Swipe left instead and you get the scroll limit tint thing flying out.

So I'm assuming we can fix this by somehow getting the view pager to handle an in-progress drag better, by taking the first event it sees and treating that (and its position) as the start of the drag. I don't know much about how ``MotionEvent``s work yet but hopefully it's not too hard to do this kind of thing

**Comment by baka-kaba** [comment]
Thinking about it, the viewpager must be seeing that initial ``ACTION_DOWN`` event, because it receives it earlier than the webview (and the javascript's "disable swipe" callback takes a while to happen anyway). So it's probably aware that a drag is in progress, it just has a blackout until swiping is enabled again
- drag starts at ``x, y``
- gets a few motion events at ``x+15, y+10`` or so
- swiping is disabled
- ............
- swiping enabled, next movement event has the finger at ``x+1000, y+2000``
- viewpager goes wow that was a big move, *yoink*

this is probably why the crash in #588 is happening too - there's a call to ``beginFakeDrag`` that probably fails because the viewpager is already aware of a real drag in progress. Maybe there's a way to cancel that or otherwise reset it

**Comment by baka-kaba** [comment]
Fixed in #591
