### ISSUE TITLE
Volume button scrolling in thread list

### ISSUE THREAD

**Issue by taiyoko** [Awful/Awful.apk#445]
I used to be able to scroll through the thread list in a subforum with the volume button scrolling enabled, since I updated to latest on the play store, it only works in the main forums view and reading threads.

**Comment by Sereri** [comment]
Oh, you're right.

It seems there was a mix-up with identical function names accepting identical parameter data types, responsible for widely different things.

So instead of scrolling 0px on the x axis and ***px on the y axis, we scrolled 0px on the y axis and took ***ms for the scroll animation it.

Thanks for reporting, it will be fixed in the next version 🙂
