### ISSUE TITLE
Bump minSdkVersion to 19 (Kitkat)

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#571]
**Impact:** According to Google Play versions 4.03-4.3 account for 297 users (~0.6%), Crashlytics counts only 30 of them as daily active users

**Why:** While there will be also minor code simplification, the most important change is the Chromium webview. This would mean that we would finally have a (relatively) common and "modern" HTML, CSS and most importantly JS feature set. This in turn would for example allow us to eliminate Zepto.js and rewrite the app's JS code to pure JS which should provide a performance boost.

**But:** Even Kitkat is now more than 4 years old. Moving up to Lollipop (API 21) would affect 750 (4%) users according to Google Play, 150 of which are active according to Crashlytics. Changing to version to 21 would again bring minor code simplification but more importantly make a version with updatable system webview a requirement. This is not (/should not be) necessary for the JS changes above though.

**Comment by baka-kaba** [comment]
A javascript boost would definitely be good, since it's such a big part of the app.

Is the updating WebView thing a big issue? I know a lack of it means previews don't work, but at least it behaves when that happens, and it's on the user to update or upgrade. Seems like a bunch of phones with custom roms tend to ship their own (broken) webview implementation too, so there'll always be people asking about their issues

4% feels pretty big to me (although they're not all active yeah)

**Comment by Sereri** [comment]
Well the 4% aren't getting the app removed, it just won't update any longer.

The updating part is just as far as being able to expect parity between all clients and them behaving the exact same (if properly updated). I'm not sure it will make much of a real impact.

**Comment by baka-kaba** [comment]
Yeah I meant to say it might not be too bad since the app doesn't update that often anyway, although to be honest that depends on whether the site does something that breaks everything (very possible)

Also this might not be the best place to mention it, but have you seen those warnings in the console?
``Upcoming versions will block content-initiated top frame navigations to data: URLs. For more information, see https://goo.gl/BaZAea``

**Comment by Sereri** [comment]
As I wrote in #578 , due to missing support for a couple of functions needed to replace zepto I will set the minimum version to Lollipop after all. I'll test some more but as far as I can see raising the API level should be sufficient, if not I can try to detect the webview version.

**Comment by baka-kaba** [comment]
This is done now right? There's a few things that can be cleaned up too, references to pre-Lollipop build codes and API-target annotations, v21 drawables and layouts and so on. We could do with sweeping through all the lint inspections, there's a lot of simple stuff that could be taken care of in a PR

**Comment by Sereri** [comment]
Yeah, I just "fixed" what I could think of from the top of my head. Not sure what makes sense to clean up before the Kotlin transition though

**Comment by baka-kaba** [comment]
I think just paring anything down is helpful, a lot of it has automatic fixes anyway. Honestly I think the transition to Kotlin will be a slow process, there's too much undocumented or unexpected behaviour in the app to go all-in at once. But unpicking it and trimming out unwanted stuff will make that a lot easier

I'll probably have a go at some of it once I've fixed this issue I'm working on
