### ISSUE TITLE
Forum list scraper fails when you're on probation (apparently)

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#596]
This needs investigating - I'm assuming when you're probated either the page structure changes enough that the whole parser falls over, or some forums fail because you're not allowed to view them, which would count as a failure to parse the entire tree. The latter's more likely, and when the update task fails, it doesn't replace the current data

This isn't really an issue (if you're on probation you can just stick with the stale forums list) except if you have no forums data (like on a new install), in which case it'll look like nothing's happening. This probably needs to be handled more generally, I'm guessing being probated causes a bunch of other issues (e.g. trying to access now-blocked forums, trying to reply to threads etc.)

**Comment by Lutha** [comment]
I'm using the second beta version of 3.6.0 and I can confirm that a fresh install of the app fails to retrieve the forum index data, if one is on probation. When the app starts, the forums list (or background?) is blank except for a message saying "No forums data". A pinwheel then spins for a moment, disappears, and then a toast message appears that says "Couldn't get forums data. Check your connection and restart".

That said, other things seem to work OK. I can view my user bookmarks page, tap on a thread there, and the tapped thread opens correctly. I can load my PMs and read them, but I didn't try sending any.

**Comment by baka-kaba** [comment]
Damn, I forgot about this. I got probed recently and fixed a few things up - yeah PMs work fine

I know it was throwing ``AwfulError``s if it detected you were on probation, which is bad because that's not actually an error! So maybe that's still happening

What's the message in your logcat @Lutha , if you can see it? Probably anything under ``CrawlerTask`` or ``UpdateTask``. I dunno if you have Android Studio installed, if not don't worry about it!

**Comment by Lutha** [comment]
Trip report. I'm using Android Studio (AS), 3.2.1 version. I had an existing Awful.apk project in AS from a few days ago, which I created using an "import from Git" type function in the new-project wizard. I first tried checking out and building the commit with the message that starts "Stopped videos being in your face ..." but it just repeatedly crashed on my device. I am not very experienced with this so I tried a different tactic.

I started by deleting from my device both the Awful beta version app that was installed via Play store, and the "Awful (debug)" app that was put on my device from the attempt to build/run. I then cleaned my build in AS and checked out the "3.6.0 beta, second try. ..." commit, which I am not sure but I think is the beta build that was on my device for the last few days, from the Play store. This build, uh, built. The app then starts as normal and I am successful at logging in. Then I look through logcat for clues.

There are no Assert-level log entries. For Error entries, mostly there are a lot of these:

`com.ferg.awfulapp.debug E/AwfulError: Error: 4 - You are under probation.`

The only other Error entries are two of these:

`com.ferg.awfulapp.debug E/NetworkUtils: now.compareTo(expiryDate):longnumberidontunderstand`

These two entries appear to happen after Android lifecycle state changes.

There aren't any log entries that mention `UpdateTask` whatsoever. There is an area of the log that mentions `CrawlerTask` quite a bit. It is right after a log line that is called `W/NetworkUtils: Cookie dump: bbuserid=#####` which appears to my untrained self to be a hex/dec/something readout of cookie data. After this line, which I won't include because I guess that it probably includes some private data, is a bunch of entries, some of which include `CrawlerTask`. A file with the text of these log entries is attached. The last few lines of the attached file show that the app *is* indeed still parsing the base forums list somehow. I did save the full log text though in case something after those lines is useful. I've also used the string `oh is this a secret code lol` to censor one string of numbers and stuff in the file (sorry) because I don't know if the numbers
[probation.txt](https://github.com/Awful/Awful.apk/files/2701143/probation.txt)
 are sensitive.

**Comment by baka-kaba** [comment]
Oh hey @Lutha thanks for all the info! You should log out and back in (maybe on all your devices) though, that cookie wasn't meant to be out in public!

Yeah I see the problem here, request responses all run through this ``AwfulError`` method that looks for problems on the page, and one thing it looks for is probation messages. If it finds one it produces a probation ``AwfulError``, but that's not actually an error!

So most request classes do this ``isCritical`` check that is effectively "is this something other than a probation" and ignore it otherwise, but the forum update requests aren't doing that check. It's an easy fix, I'll need to get probed to test it though

**Comment by baka-kaba** [comment]
Also while I'm here, someone says the Leper's Colony is doing it too, so I need to check that. Is there a todo list on here

**Comment by Lutha** [comment]
@baka-kaba yes, I believe this error was being thrown when I tried to view Leper's Colony as well. I'm not on probation any more though so I can't check for sure.

**Comment by baka-kaba** [comment]
Yeah don't worry, I'll sort it out when I get round to getting probed

> A todo list? Does this look like an iOS app to you?

I think we've nailed the aesthetic tbh
