### ISSUE TITLE
The frog did a milkshake duck

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#612]
Allow the user to chose a non-frog app icon

Since the background of the app loading placeholder can not be dynamically changed as well, it should become more generic. Preferably just a white "AWFUL" in Roboto.

**Comment by baka-kaba** [comment]
It could be Roboto, _or_ it could be *cool typography*. Maybe some designer can pick out a cool one?

Also since Spanky did a bunch of icons, maybe we could use those for a splash image. Lined up like a cast of characters, or something. That way it's not like "the frog app" but... oh god there are frogs all over the app aren't there

**Comment by Sereri** [comment]
See https://github.com/Sereri/Awful.apk/commit/5cdb3ad76d79d2ed99f544dcd0e418316246ebba for an example of icon swapping.
Needs some things like properly implemented icons, better variable names and a selection dialog if we have more than 2 icons.
And a warning, that this deletes the icon from the homescreen. Oh and that it doesn't work when Nova Launcher is Oreo-ing the icon shapes.
