### ISSUE TITLE
Allow fullscreen on videos

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#622]
Allow videos in the webview to play videos fullscreen. 

Working POC that needs a bit of cleaning up and lots of polish:
https://github.com/Sereri/Awful.apk/tree/webviewFullscreenPOC

Adaptation of:
https://github.com/akhgupta/WebviewVideo

@baka-kaba do you have anything in the works that collides with the (horrible) changes to the webview?

**Comment by baka-kaba** [comment]
I don't think so, my webview poking is pretty much just on the "display these posts instead" side at the moment.

That build works, it's not actually fullscreen though - it just fills the thread page, right?
I tried using a dialog to hold the view instead, take a look and see what you reckon 7b2aad77d655e8d5d52a2cd6f0432ac9683f590a
I removed the changes I wasn't using, can probably drop the webview reference too and pass in a context instead, unless hiding it is important

**Comment by baka-kaba** [comment]
Oh also the context menu is good! So much better

**Comment by Sereri** [comment]
Oh wow the dialog is much better. If we could hide navigation bar as well it would be perfect but I'd take it like this as well.

**Comment by baka-kaba** [comment]
I had a quick go and I've added a commit - the good news is it's pretty simple to make it immersive, you just set the flags on the View you get handed. The bad news is the Activity doesn't seem to want to automatically unhide the stuff when it gets focus back, even though the flags aren't set and you can explicitly update the layout - it doesn't trigger until the user swipes up or opens the nav drawer or that kind of thing.

Know any tricks for giving it a kick? Or is this fine as-is?

**Comment by Sereri** [comment]
I think this works as is. You can still go back with the un-fullscreen icon of the video. I actually looked how Youtube is doing it and it's exactly the same. Unless there is something you want to clean up first, feel free to merge it.

**Comment by baka-kaba** [comment]
No I mean when you click the full-screen button again, you're back at the activity, but the navigation buttons and status bar are still missing. The window setup callback is fired and works, and the hiding flags aren't set (I've tried explicitly setting them as off too) but the activity still hides them until the user interacts with the screen - either touching the top or bottom, or swiping the viewpager

It's not a big deal, I don't think anyone's gonna get lost beyond an initial "hey where's the things", but it looks a bit janky. The youtube app just has them right there when you come back from fullscreen, but for some reason I can't get it to happen with ours

I'll commit it if you're cool with how it is though - seems like an ok tradeoff to me, maybe we can fix it later

**Comment by Sereri** [comment]
:psyduck: I didn't notice that, and it seems to stick if you have
orientation change disabled.
I'll try to find something to combat this

baka-kaba <notifications@github.com> schrieb am Sa., 14. Juli 2018, 20:12:

**Comment by Sereri** [comment]
I finally took a look and tried various things and the only thing that worked somewhat was pausing and then playing the video on return from the fullscreen. However I can't get the timing down so it doesn't work most of the time. It would be easier if I could pause the video when exiting the fullscreen. I tried that, and as it turns out its some freak chromium view and trying to pause that was unsuccessful even with reflection and such.

**Comment by baka-kaba** [comment]
Ah man yeah, it's lucky it works as cleanly as it does I think. Shall I just merge it as-is? I'm sure we'll end up with lots of posts saying THE BUTTONS DISAPPEAR but that's web development guys

I'll try re-applying and immediately reverting the fullscreen flags when the activity regains focus to see if that does anything, but I doubt it

**Comment by baka-kaba** [comment]
All right so I added another commit - it uses a Handler to set the "show UI" flag, so the stable layout can be set up first, and then the UI can pop back in.

The good news is it works. The bad news is... I have no clue what's going on, it just triggers whenever it likes! The delayed runnable has a logging line in it, so you can see when the runnable is called, but the UI can appear any time before that - I have no idea when or how that code is being called! But it is being called, because remove that line and it doesn't work. Just setting that flag instead of the LAYOUT_STABLE one doesn't work. Seems like it has to be a posted runnable, but it just magically happens whenever

Anyhow, I put it on a 5-second delay for testing, I'd go with 1 second or maybe half. When it triggers later it looks good, the layout is stable and the stuff just slides back in. When it happens early it all jumps about a bit - but it always seems to end up laid out right with everything visible, so it *works*. Good enough?

There's also an issue that the video isn't always visible when you go fullscreen (you can swipe to show it) but it's there - you can interact with the controls, you just can't see anything 🤷‍♂️

**Comment by baka-kaba** [comment]
Added in #629
